### ISSUE TITLE
I got this error sometime

### ISSUE THREAD

**Issue by veyhong** [Colu-platform/colu-nodejs#23]
```
/app/node_modules/colu/src/colu.js:80
assetInfo.txid = resp.txid2.txid
^
TypeError: Cannot read property 'txid' of undefined
at /app/node_modules/colu/src/colu.js:80:32
at /app/node_modules/async/lib/async.js:52:16
at /app/node_modules/async/lib/async.js:1209:30
at Request._callback (/app/node_modules/colu/src/colu.js:114:5)
at Request.self.callback (/app/node_modules/colu/node_modules/request/request.js:199:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:194:7)
at Request.<anonymous> (/app/node_modules/colu/node_modules/request/request.js:1036:10)
at emitOne (events.js:101:20)
at Request.emit (events.js:191:7)

```
I just recently got this kind of error, can anyone help me out.

**Comment by oleiba** [comment]
Thanks for reporting.
solved [a181425](https://github.com/Colu-platform/colu-nodejs/commit/a1814259a930a011f7d4d46cdce498b3f315d716).
