### ISSUE TITLE
Connecting to Redis doesn't work on new version

### ISSUE THREAD

**Issue by dukedorje** [Colu-platform/colu-nodejs#4]
We upgraded the colu npm module.  This is on my localhost, and redis is running on the default port.
```
Unhandled rejection TypeError: Cannot read property 'hset' of undefined
  at [object Object].HDWallet.setDB (/Users/dorje/work/CitizenCode/swarmbot/node_modules/hdwallet/src/hdwallet.js:159:10)
  at [object Object].HDWallet.setNextAccount (/Users/dorje/work/CitizenCode/swarmbot/node_modules/hdwallet/src/hdwallet.js:219:8)
  at [object Object].HDWallet.getPrivateKey (/Users/dorje/work/CitizenCode/swarmbot/node_modules/hdwallet/src/hdwallet.js:403:10)
  at async.waterfall.privateKey (/Users/dorje/work/CitizenCode/swarmbot/node_modules/colu/src/colu.js:128:56)
  at fn (/Users/dorje/work/CitizenCode/swarmbot/node_modules/async/lib/async.js:741:34)
  at /Users/dorje/work/CitizenCode/swarmbot/node_modules/async/lib/async.js:1208:16
  at /Users/dorje/work/CitizenCode/swarmbot/node_modules/async/lib/async.js:166:37
  at /Users/dorje/work/CitizenCode/swarmbot/node_modules/async/lib/async.js:701:43
  at /Users/dorje/work/CitizenCode/swarmbot/node_modules/async/lib/async.js:167:37
  at Object.async.waterfall (/Users/dorje/work/CitizenCode/swarmbot/node_modules/async/lib/async.js:705:44)
  at [object Object].Colu.issueAsset (/Users/dorje/work/CitizenCode/swarmbot/node_modules/colu/src/colu.js:125:9)
```

**Comment by dukedorje** [comment]
we were initializing the library improperly...
